open_door:
  fields:
    device_id:
      required: true
      example:
        - 1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d
      selector:
        device:
          integration: vidos_x
    door:
      default: 0
      selector:
        number:
          min: 0
          max: 16
    lock:
      default: 0
      selector:
        number:
          min: 0
          max: 16
    password:
      example: "1234"
      selector:
        text:
